### PR TITLE
Add more metadata for Mod Menu

### PR DESCRIPTION
**Pull request by Prospector**
Icon is public domain from Wikipedia https://commons.wikimedia.org/wiki/File:Listermillsbradford.jpg

### CODE REVIEW

**Comment by MrIbby** [comment]
don’t forget homepage

**Comment by Prospector** [comment]
lol sorry I didn't see your PR until after I made mine

**Comment by MrIbby** [comment]
lol I know what it's like

**Comment by Chocohead** [comment]
Icon looks entertainingly ugly being so small but I'll take it none the less

**Pull request merged**
